version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finstream_batch
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/finstream

  db:
    image: postgres:13
    container_name: finstream_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finstream
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: